// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phlhdwhzxrxovznjodtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobGhkd2h6eHJ4b3Z6bmpvZHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTk1MzMsImV4cCI6MjA3NDQ5NTUzM30.B60eGzjlsp-AqTdL5Su9vO1LHmr3tGfHmodAXp1C3zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});